### PR TITLE
Include tupande and erply in bpmn.processes

### PR DESCRIPTION
**Pull request by victorjbassey**
## Description

* Added entries for erply and tupande, so that their transactions can be seen on operations web.

@truthfool @fynmanoj please review

### CODE REVIEW

**Review by fynmanoj — COMMENTED** [review]
LGTM @truthfool  please check

**Comment by truthfool** [comment]
_ should be used if you are using DFSPID.
Here inbound_transfer_tupande

**Comment by victorjbassey** [comment]
> _ should be used if you are using DFSPID. Here inbound_transfer_tupande

@truthfool the existing ones for roster (inbound_transfer-roster) and paygops (inbound_transfer-paygops) do not use _
Can you check those, and let me know if that needs to change too?

**Comment by truthfool** [comment]
The - will work. But while deployment it will deploy as _. So no issues if you give it as -.

**Pull request merged**
